version: '3'
services:
    user-srv:
        build: .
        container_name: "user-srv"
        environment: 
            - DATABASE=${MONGO_DATABASE}
            - USERNAME=${MONGO_USERNAME}
            - PASSWORD=${MONGO_PASSWORD}
        ports:
            - 8080:8080
        depends_on:
            - mongodb
    mongodb:
        image: "mongo:latest"
        container_name: "mongodb_container"
        ports:
            - 27017:27017
        environment: 
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
             # seeding scripts
             - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            # named volumes
             - ./mongodb:/data/db
volumes:
    mongodb: